### ISSUE TITLE
[Bug] after I choose the sprite location folder it never opens

### ISSUE THREAD

**Issue by Cyndr4** [jngo102/sprite-packer#1]
### Describe the bug

when i try to open spritepacker it just opens up "choose where to get the sprites" or whatever that popup is, and never actually opens. helpgdfdfdf

### User platform and version

```shell
using windows 11
```

**Comment by jngo102** [comment]
Did you select the path to the folder containing all your sprites?

**Comment by Cyndr4** [comment]
yeah, multiple times. still continued to close though

**Comment by jngo102** [comment]
If it exists, please show your log output located at `%APPDATA%/sprite-packer/config/sprite-packer.log`.
